name: Majsoul-Login
on:
  workflow_dispatch:
  schedule: #5:00
   - cron: '30 21 * * *'

# 解决 Node.js 20 废弃警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  login:
    name: Majsoul-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 仅保留 Python 版本配置，移除缓存配置

      - name: Install Selenium
        run: pip install selenium==4.17.2

      - name: Majsoul login
        run: python login.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}
